---
format: html
---
## Exercício 4

```{r}
dbetaretang <- function(x, a, b, p) {
  if(x < 0 | x > 1) return(0)
  else return((1 - p) * 1/beta(a, b) * x^(a-1) * (1-x)^(b-1) + p)
}

pbetaretang <- function(x, a, b, p) {
  
  integrate(dbetaretang, lower = 0, upper = x, a = a, b = b, p = p)[[1]]
  
}

dbetaretang <- Vectorize(dbetaretang, vectorize.args = 'x', SIMPLIFY = TRUE)
pbetaretang <- Vectorize(pbetaretang, vectorize.args = 'x', SIMPLIFY = TRUE)

rbetaretang_estocastica <- function(n, a, b, p) {
  bernoulli_vec <- sample(c(0, 1), size = n, replace = TRUE, prob = c(1 - p, p))
  result <- numeric(n)
  
  for(i in seq_along(bernoulli_vec)) {
    if(bernoulli_vec[i] == 0) result[i] <- rbeta(1, a, b)
    else result[i] <- runif(1)
  }
  
  return(result)
}

rbetaretang_rej <- function(n, a, b, p) {
  unif_vec <- runif(n)
  result <- numeric(n)
  
  u <- 0.3
  sigma <- 0.4
  C <- 1.63909
  
  for(i in seq_along(unif_vec)) {
    x <- rnorm(1, u, sigma) # sd = sqrt(4)
    
    while(unif_vec[i] > dbetaretang(x, a, b, p)/(dnorm(x, u, sigma) * C)) x <- rnorm(1, u, sigma)
    
    result[i] <- x
  }
  
  return(result)
}

rbetaretang_inv <- function(n, a, b, p) {
  unif_vec <- runif(n)
  result <- numeric(n)
  
  for(i in seq_along(unif_vec)) {
    result[i] <- uniroot(function(x) {pbetaretang(x, a = a, b = b, p = p) - unif_vec[i]}, interval = c(-0.1, 1.1))$root
    
  }
  
  return(result)
}

```

```{r}
n <- 5000
a <- 2
b <- 3
p <- 0.2

dados <- rbind(
  data.frame(
    Método = 'Estocástico',
    Valor = rbetaretang_estocastica(n, a, b, p)
  ),
  data.frame(
    Método = 'Rejeição',
    Valor = rbetaretang_rej(n, a, b, p)
  ),
  data.frame(
    Método = 'MTI',
    Valor = rbetaretang_inv(n, a, b, p)
  )
)

ggplot(
  dados,
  aes(x = Valor, color = Método)
) +
  geom_density() +
  geom_function(aes(color = 'Densidade'), fun = dbetaretang, args = list(a = a, b = b, p = p))

```
```{r}
mean(dados %>% filter(Método == 'Estocástico') %>% pull(Valor) %>% log())
```




