# Questão 4

Os resultados das aproximações por Monte Carlo foram comparadas com os resultados obtidos utilizando o site [emathhelp.net](emathhelp.net).

```{r}
#| echo: false
n <- 5000
library(tidyverse)
library(knitr)
```


```{r}
rexp_truncada <- function(n, rate = 1, lower = 0, upper = Inf) {
  result <- numeric(5000)
  for(i in seq_along(result)) {
    y <- rexp(rate)
    while(y < lower | y > upper) y <- rexp(rate)
    result[i] <- y
  }
  return(result)
}
```

```{r}
lista_g <- list(
  a = function(x) (1-x^2)^(3/2),
  b = function(x) 4*exp(x+x^2),
  c = function(x) pi / 3 * sin(x),
  d1 = function(x) exp(-x) / (1 + x^2),
  d2 = function(x)1/(1+x^2) * pexp(1)
)
lista_gerar_f <- list(
  a = expr(runif(n)),
  b = expr(runif(n, -2, 2)),
  c = expr(runif(n, 0, (3 / pi))),
  d1 = expr(runif(n)),
  d2 = expr(rexp_truncada(n, upper = 1))
)
result1 <- numeric(5)
for(i in seq_along(lista_g)) {
  g <- lista_g[[i]]; g <- Vectorize(g)
  sim_f <- eval(lista_gerar_f[[i]])
  result1[i] <- mean(g(sim_f))
}
```

```{r}
#| echo: false

n <- 100
tabela2 <- data.frame(
  Integral = c(
    '$\\int_0^1(1 - x^2)^{3/2}dx$',
    '$\\int_{-2}^{2} e^{x + x^2} dx$',
    '$\\int_{0}^{\\pi/3} \\sin(x) dx$',
    '$\\int_{0}^{1} \\frac{e^{-x}}{1 + x^2}dx$',
    '$\\int_{0}^{1} \\frac{e^{-x}}{1 + x^2}dx$',
    '$\\int_{0}^{1} \\left(\\int_{0}^{1} e^{x+y}dx \\right) dy$',
    '$\\int_{0}^{1/3}\\int_{0}^{2/3} x^3 y^2 (1- x - y)^6dx dy$'
  ),
  distxy = c(
    '$U(0,1)$',
    '$U(-2, 2)$',  
    '$U(0, \\frac{\\pi}{3})$',
    '$U(0,1)$',
    '$exp_{(0, 1)}(1)$',
    '$U(0,1)$',
    '$U(0, \\frac{2}{3})$'
  ),
  disty = c(
    '-',
    '-',
    '-',
    '-',
    '-',
    '$U(0, 1)$',
    '$U(0, \\frac{1}{3})$'
  ),
  fx = c(
    '$\\mathbb{1}_{(0, 1)}(x)$',
    '$\\frac{1}{4} \\mathbb{1}_{(-2, 2)}(x)$',
    '$\\frac{3}{\\pi} \\mathbb{1}_{(0, \\frac{\\pi}{3})}(x)$',
    '$\\mathbb{1}_{(0, 1)}(x)$',
    '$\\frac{e^{-x}}{F_{exp(1)}(1)} \\mathbb{1}_{(0, 1)}(x)$',
    '$\\mathbb{1}_{(0, 1)}(x)$',
    '$\\frac{3}{2} \\mathbb{1}_{(0, \\frac{2}{3})}(x)$'
  ),
  fy = c(
    '-',
    '-',
    '-',
    '-',
    '-',
    '$\\mathbb{1}_{(0, 1)}(y)$',
    '$3 \\mathbb{1}_{(0, \\frac{1}{3})}(x)$'
  ),
  g = c(
    '$(1 - x^2)^{3/2}$',
    '$4e^{x + x^2}$',
    '$\\frac{\\pi}{3} \\sin(x)$',
    '$\\frac{e^{-x}}{1+x^2}$',
    '$\\frac{F_{exp(1)}(1)}{1+x^2}$',
    '$e^{x + y}$',
    '$x^3 y^2 (1 - x - y)^6 * \\frac{2}{9}$'
  ),
  externo = c(
    0.589043,
    93.16275,
    0.5,
    0.52479,
    0.52479,
    2.952492,
    1.192724e-06
  )
)
```

```{r}
lista_gerar_fx <- list(
  e = expr(runif(n)),
  f = expr(runif(n, 0, 2/3))
)
lista_gerar_fy <- list(
  e = expr(runif(n)),
  f = expr(runif(n, 0, 1/3))
)
lista_g <- list(
  e = function(x, y) exp(x + y),
  f = function(x, y) x^3 * y^2 * (1 - x - y)^6 * 2 / 9
)
result2 <- numeric(2)
for(i in seq_along(lista_gerar_fx)) {
  sim_x <- eval(lista_gerar_fx[[i]]); sim_y <- eval(lista_gerar_fy[[i]])
  fun_g <- lista_g[[i]]; fun_g <- Vectorize(fun_g)
  dados <- expand_grid(x = sim_x, y = sim_y) %>%
    mutate(g = fun_g(x, y))
  result2[i] <- sum(dados$g) / n^2; rm(dados)
}
tabela2[['Monte Carlo']] <- c(result1, result2)
```

```{r}
#| echo: false

kable(
  tabela2[, 1:6],
  col.names = c('Integral', 'Dist. $X$', 'Dist. $Y$', '$f_X(x)$', '$f_Y(y)$', '$g(x)$')
)

```

```{r}
#| echo: false

kable(
  tabela2[, c(1, 7:8)],
  col.names = c('Integral', 'Site', 'Monte Carlo')
)

```
